version: '3.8'

services:
  localstack-local:
    image: localstack/localstack:latest
    container_name: localstack-local
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1

  rabbitmq-local:
    image: rabbitmq:3-management
    container_name: rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
