server:
  port: 8080
spring:
  application:
    name: "ch-ms-user-interaction-stats"
  devtools:
    add-properties: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: local
    include: null
aws:
  region: us-east-1
  dynamodb:
    endpoint: "http://localhost:4566"
    tables:
      user-interaction-stats: UserInteractionStats
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"


